# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('referencia', models.IntegerField(default=0)),
                ('debito', models.FloatField(default=0)),
                ('credito', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('tipo_de_saldo', models.CharField(choices=[('d', 'Debito'), ('c', 'Credito')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('naturaleza', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro_diario.Clase')),
            ],
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro_diario.Grupo'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro_diario.Cuenta'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro_diario.Fuente'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro_diario.Tercero'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together=set([('nombre', 'clase')]),
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together=set([('nombre', 'grupo')]),
        ),
    ]
